### ISSUE TITLE
Run linting outside of VSCODE

### ISSUE THREAD

**Issue by JDubb-At-Nelnet** [codefori/vscode-rpgle#111]
This is an awesome tool - i was wondering if there was a way to use it outside of the context of VSCODE?

Things I would like to do
 - Define some linting rules, call a command or program passing a library / file / member name as input and get back something that tells me if the member passes all linting rules.  This would be awesome to incorporate into a CI/CD pipeline.
 -  Run a command that fixes all automatically fixable lint errors.

**Comment by worksofliam** [comment]
Hi @JDubb-At-Nelnet !!

Yes, this is going to happen. I have already started the work to move all the parsing stuff out of this repo into another base library. The timeline is long but it'd be a great achievement. 

I am aiming at something like: `rpglint /path/to/source.rpgle`, and of course many complex options, including entire directory scanning!

**Comment by worksofliam** [comment]
We did this!
