### ISSUE TITLE
RPGLINT Slow

### ISSUE THREAD

**Issue by HenryMiller** [codefori/vscode-rpgle#193]
I'm using RPGLINT Extensions with basic settings.
I've found, especially in the last 15 days, that RPGLINT extension is  really slow after a while and I have to disable it if I want to continue editing my  local RPGLE source code.
Immediately after it has been disabled then source editing works absolutely fine.

{
  "indent": 3,
  "PrototypeCheck": true,
  "NoOCCURS": true,
  "NoSELECTAll": true,
  "UppercaseConstants": true,
  "IncorrectVariableCase": true,
  "StringLiteralDupe": true,
  "NoSQLJoins": true,
  "PrettyComments": true,
  "NoGlobalSubroutines": true,
  "NoExternalTo": [
    "QCMD",
    "QP2TERM",
    "QSH",
    "SYSTEM",
    "QCMDEXC"
  ]
}

* QCCSID: 1144
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "£§$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: La libreria ILEDITOR esiste già.",
    "cwd": "/ospreys/m11/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Non trovato l'oggetto QCPTOIMPF nella libreria QSYS.",
    "cwd": "/ospreys/m11/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Non trovato l'oggetto QCPFRMIMPF nella libreria QSYS.",
    "cwd": "/ospreys/m11/"
  }
]
```

**Comment by HenryMiller** [comment]
@worksofliam Source code is not that big , between 100 and 800 lines. It's slow at scrolling as well. Sometimes it's slow when saving. 

Just one thought.
Is it slow because RPGLE source code is in a directory  inside a main project which includes a FrontEnd and Backend directory and RPGLINT is scanning the whole source project  members (Frontend=Angular Backend=RPGLE).
For testing purposes I copied one source member into my desktop folder and editing from there  looks much faster. 
 
I attach an example. 
[sq000s.txt](https://github.com/halcyon-tech/vscode-rpgle/files/10412331/sq000s.txt)
<img width="142" alt="image" src="https://user-images.githubusercontent.com/1829995/212344089-5467073a-c875-49c5-9a37-008701ce53ca.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1829995/212346593-17262f0f-ba2d-4b0f-8891-07b878cd1810.png">

**Comment by worksofliam** [comment]
Ok, thanks for letting me know of your scenario. I will see if I can recreate it.

**Comment by HenryMiller** [comment]
Hi,
did you get any chance to recreate and test it.
Thanks
