### ISSUE TITLE
The RPGLE language client server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by SJLennon** [codefori/vscode-rpgle#254]
Not a major impediment, but reporting anyway.
Running latest version of the extension, 0.21.3 in Windows 10..

Very simple steps to recreate:

1. Start  VS Code with no folders open and no tabs open.
2. Do not connect to IBM i.
3. Open a _local_ folder with files with an .RPGLE extension.
4. Open a file with the .RPGLE extension.
5. This is displayed:

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/67484051/4fb1d42e-b361-409b-90e3-e961717ac78f)

There is a mass of stuff in the output.  Here's the top:
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/67484051/905efe04-9f94-4b74-aa04-25ab33cf9fd1)

This is my very simple folder structure on my C: drive:
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/67484051/6dcad549-6e36-4b1f-8d08-7a8ece9b31b9)

**Comment by worksofliam** [comment]
Tried to recreate it with no luck. Any chance you can show share the entire output?

**Comment by SJLennon** [comment]
@worksofliam 
Sure.  Here it is.
[Output.txt](https://github.com/halcyon-tech/vscode-rpgle/files/12539414/Output.txt)

**Comment by bmcpherson-srlife** [comment]
Good morning,

I also happened to encounter this issue when opening Visual Studio. It was working fine yesterday with no errors, but when I opened it this morning, the same "client server crashed 4 times in the last 3 minutes" message appeared. I had files open automatically from a previous session, a mixture of SQLRPGLE file members and files (SQL, SQLRPGLE, and RPGLLE) from a project folder on the IFS, if that helps with any attempt at recreating the issue. 

Crash Log for RPGLE Extension v0.21.4
[rpgle_extension_crashlog.txt](https://github.com/halcyon-tech/vscode-rpgle/files/12619247/rpgle_extension_crashlog.txt)

**Comment by worksofliam** [comment]
Thanks folks. I am going to look further into this next week.

**Comment by JDubbTX** [comment]
This is also hitting me for the last few days.

**Comment by JDubbTX** [comment]
https://github.com/JDubbTX/IBMiExamples crashes whenever I open anything in QRPGLESRC.  Running in windows > wsl > ubuntu devcontainer

**Comment by JDubbTX** [comment]
Confirmed v0.20.2 was the last working version of the extension for me.
<img width="944" alt="image" src="https://github.com/codefori/vscode-rpgle/assets/56802156/a90066cd-dff5-4524-9278-e8a2e79db77b">
<img width="950" alt="image" src="https://github.com/codefori/vscode-rpgle/assets/56802156/832608d0-1ae8-446b-b2b3-b737ea99d928">

**Comment by JDubbTX** [comment]
Forked it and ran locally, here is the output:
[Debugger listening on ws127.0.0.187.txt](https://github.com/codefori/vscode-rpgle/files/13113487/Debugger.listening.on.ws127.0.0.187.txt)

**Comment by worksofliam** [comment]
@JDubbTX You are fantastic. That log was exactly what I needed. Thank you! I am going to make a small release of this today.

**Comment by JDubbTX** [comment]
OK, more info:  The issue doesn't occur on my work development lpar.  It only occurs when I'm connected to PUB400.  I think the permissions errors had something to do with it.  I'll try out the new release and see if that fixes it on both.

**Comment by JDubbTX** [comment]
@worksofliam I updated to RPGLE to 0.22.1, did a reload, and now the problem is fixed for me.  Thanks!
