### ISSUE TITLE
RPGLE Linting configurability

### ISSUE THREAD

**Issue by sudhiraroraCVS** [codefori/vscode-rpgle#264]
Hi Team,

I work in CVS Health and was exploring Linting feature of RPGLE on VS Code for our discovery project on VS Code. Linting is a really good feature which is not available in RDI and we know RPGLINT.JSON file can some pre-defined linting parameters to enforce the rules but we want to use this feature to next level if there is way to add/configure our own rules for linting so that we can better use this feature of VS Code. 
Our Use case is  : We have Dev code check list with a long list which our developers performs manual check on the code and we want to automate that. I know we can user Sonarqube scans which are available for RPGLE but that is too late in the game when code goes through CI pipeline. We want to enforce/configure our own rules during coding time so that we can force developers to fix the code early in the game.

We have huge list of Dev code checklist but below is 1 example from that list which we may want to add in RPG linting. So we want to understand if we have flexibility to add rules like below in RPG linter or we are just restricted to use pre-defined rules only.
Please suggest. 
Check list item : Has SETLL and READE been used instead of CHAIN for performance.? 

Thanks
Sudhir.

**Comment by sudhiraroraCVS** [comment]
Thanks for the detailed response. There is a mention of creating our own extension and then we can add our rules. Can you share the steps to create our own extension or in case you have any reference then that would be great.

**Comment by worksofliam** [comment]
@sudhiraroraCVS See the guide here: https://code.visualstudio.com/api/get-started/your-first-extension

I am going to close this issue now. Thanks.
