### ISSUE TITLE
Question: what about unused variables check? 

### ISSUE THREAD

**Issue by Alastyr** [codefori/vscode-rpgle#289]
Hi everyone.
RDI checks for unused variables, but I don't find the same option in the vscode linter. 
Is this feature available in vscode extension?

Thanks everyone

RDI
![image](https://github.com/codefori/vscode-rpgle/assets/1959505/c3547319-2820-4cd0-a95f-ffb18e2c8925)

VSCode
![image](https://github.com/codefori/vscode-rpgle/assets/1959505/247aea6b-fde1-45d9-a443-f6fd49f4cdd0)

**Comment by worksofliam** [comment]
It is possible to enable this with an RPG lint config option: `NoUnreferenced`
