### ISSUE TITLE
Convert to free format issues

### ISSUE THREAD

**Issue by Alastyr** [codefori/vscode-rpgle#290]
Hi,
this variable declaration is not converted correctly.

`D QprObj                          a   len(500000) varying`

`QprObj         Varchar()  LEN(500000);`

![image](https://github.com/codefori/vscode-rpgle/assets/1959505/aefe969a-92fb-4fba-b5e0-fb83023dc1d4)

![image](https://github.com/codefori/vscode-rpgle/assets/1959505/0609b917-0643-420f-9489-850d23f032f7)

Same for

`D QvgTagRowSql    s         500000a   varying(4) inz('')`

`dcl-s QvgTagRowSql Varchar(500000) (4) INZ('');`

**Comment by worksofliam** [comment]
Hey! This is the wrong extension. Your issues belongs in https://github.com/BrianGarland/vscode-rpgfree

**Comment by Alastyr** [comment]
Thank you, sorry.
