### ISSUE TITLE
Column assist for RPGLE fixed-format removed?

### ISSUE THREAD

**Issue by ssamayoa** [codefori/vscode-rpgle#297]
I have to maintain and write fixed format RPG but looks like the column assist is no longer there, F1 > "RPGLE" only shows "Open RPGLE lint configuration" even tho I have checked "Show Fixed format Outliner" > "Will provide column assist for writing fixed format RPGLE (RPG3 and RPGIV)" of "RPGLE Language tools" - I can see in settings.json 

 "vscode-rpgle.showFixedFormatOutline": true

So, was removed?

I found this issue from 2022": https://github.com/codefori/vscode-rpgle/issues/84
but is not clear what was done then.

**Comment by worksofliam** [comment]
Added back. Will release soon
