### ISSUE TITLE
rpglint NPM package hasn't been updated since 0.17.5

### ISSUE THREAD

**Issue by brandonp42** [codefori/vscode-rpgle#306]
It doesn't look like the standalone rpglint package has been getting updated, can this be fixed? See https://www.npmjs.com/package/@halcyontech/rpglint

**Comment by brandonp42** [comment]
Just FYI however, there may be other issues with the latest. When I manually build and run against the main branch I'm getting a "Failed to lint... cannot read properties of undefined (reading 'start')" error on some sources that don't give an error on the old 0.17.5 version.

I haven't looked into that further yet. I was adding a feature to the rpglint CLI to filter the files to only look at changes in a recent set of git commits - ie to run via CI and report errors back.

**Comment by worksofliam** [comment]
Yes, the rpglint package needs some love. Didn't think many were using it. I can do that next week.

**Comment by brandonp42** [comment]
Right now I'm just playing with it... I'm hoping to start using it for real - I want to add it to our build pipeline to email developers with lint results based on commits to their feature branch. One of our developers is using the linting just as part of the vscode plugin though.

If you have time please take a look at the branch I'm working on and let me know if you have any concerns - https://github.com/brandonp42/vscode-rpgle/tree/add-rpglint-git-filter. I'll submit a PR though sometime soon.

**Comment by brandonp42** [comment]
Awesome, thank you!
