### ISSUE TITLE
Strange behavior of data structure subfields name autocompletion

### ISSUE THREAD

**Issue by allthom** [codefori/vscode-rpgle#308]
Hi everybody, i am here to tell you about a strange thing happening on my pcs.
I'have defined a DS like this:
```
Dcl-DS Prats Qualified Inz;
  prid packed(13:0);
  pridrac packed(13:0);
  dataPag date;
  dataVal date;
  gimocr zoned(6:0);
  gimolnd zoned(6:0);
  spese packed(11:2);
  diarie packed(11:2);
  totale packed(11:2);
  codAcgL char(6);
  cognome char(35);
  nome char(35);
  codAcgC Char(6);
End-DS;
```
Then in source when i try to write DS subfields name i get the autocompletition (see below)
![prats1](https://github.com/codefori/vscode-ibmi/assets/141107907/25c43005-d7de-427c-8e06-61f0ae31f0ba)

but if I put the name of the DS inside round brackets, I lose the suggestion of the names of the fields of the DS
![prats2](https://github.com/codefori/vscode-ibmi/assets/141107907/098a3625-b60b-4985-8168-031b27c7e89b)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.8.0|
|Visual Studio Code version|1.87.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.3.25
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.9.0
ESLint (vscode-eslint): 2.4.4
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.3
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.86.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|12|
|CCSID|65535|
|Default CCSID|280|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|
|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|iconv|GETNEWLIBL.PGM||
|ls|||
|setccsid|||
|tar|||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "��$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC9801:  Oggetto MXCMD2RUN di tipo *DTAQ creato nella libreria QTEMP.\nCPC9801:  Oggetto MXRSNDMG di tipo *DTAQ creato nella libreria QTEMP.\nCPF2111:  La libreria ILEDITOR esiste gi�.",
    "cwd": "/home/MYUSER"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPFA0A9:  L'oggetto non � stato trovato. L'oggetto � /QSYS.LIB/MYUSER.LIB/VSCODE.FILE/RPGLINT.MBR.\nCPFA097:  Oggetto non copiato. L'oggetto � /QSYS.LIB/MYUSER.LIB/VSCODE.FILE/RPGLINT.MBR.",
    "cwd": "/home/MYUSER"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"MYUSER\" && export HOST=\"172.22.46.4\" && export HOME=\"/home/MYUSER\" && export WORKDIR=\"/home/MYUSER\" && export LIBLS=\"MYUSER plus a very long library list	QTEMP\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/MYUSER"
  }
]
```
</details>

**Comment by worksofliam** [comment]
I have tried to recreate with no luck. Perhaps a video, or share the entire document/file where this is happening.

**Comment by allthom** [comment]
@worksofliam thx for your reply, any suggestion on how to make a video? Where do i have to look for the 'format on save' option? Anyway it happens on all my sources, sources are stored as pf-src member.

**Comment by angelorpa** [comment]
> I have tried to recreate with no luck. Perhaps a video, or share the entire document/file where this is happening.

@worksofliam check this video clip. My option "format on save" is disabled but it should be irrelevant. When you write the data structure inside parenthesis when open parenthesis is in the same line you lose the autocomplete suggestions for field names. Sames happens whit enums. 


https://github.com/codefori/vscode-rpgle/assets/10833316/44f68190-cf2c-4902-8ede-30364518934e

**Comment by worksofliam** [comment]
@angelorpa Your issue actually looks different from the original issue but nonetheless interesting find. Thanks

**Comment by lgiammattei** [comment]
I noticed another "strange" behavior of the autocomplete function, again with DS.
Let's say we defined a procedure block with dcl-proc; and end-proc; something like this
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/bb29cc44-4dd8-42cf-be5f-1ecdf8ccef43)
if I start writing the name of the ds inside the dcl-proc block; / end-proc; doesn't solve it for me, look at the picture
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/4846459e-06d1-4174-bf79-cbcb0a4269ab)
if instead I insert it into another block of code, perhaps an if or a do within the dcl-proc;/end-proc; it is resolved
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/9b1e308b-162d-452b-9ad7-059265c904be)
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/84288a22-cd4e-4aed-a24c-86423a94129b)
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/bfc29700-75fe-4186-8244-e5026b36b24c)
Sorry for the many images but from my devlopment pc i am unable to record a video

**Comment by worksofliam** [comment]
@angelorpa and @lgiammattei 

I have fixed your issues and released them in 0.26.4.

**Comment by angelorpa** [comment]
now It's working like a champ. Thanks.

**Comment by lgiammattei** [comment]
@worksofliam thank you, I'm sorry but it seem there is another issue with scoping.
I have this procedure long more than a couple hundreds lines of code.
I have ds defined with LIKEDS keyword
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/867ccfdb-c3e4-4ae1-a44d-36c1a69f23a9)
at line 193 it solve the names of the variables
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/b20c853c-98f1-4683-a188-66ae9d18de80)
at line 194 it looses the scope
![immagine](https://github.com/codefori/vscode-rpgle/assets/54810977/0b5c7529-bf77-41bf-ade4-775a386d8490)
:-( what's wrong with my sources?

**Comment by worksofliam** [comment]
@lgiammattei are you able to share the source with me? I'd like to be able to debug this.

**Comment by worksofliam** [comment]
@lgiammattei yes, sharing a txt file is good. GitHub Gist is also fine.

**Comment by worksofliam** [comment]
Can you share your definition of `DSAnagraficaArbitri` from your copybook?

I created a temp one like this, and I am not having issues - so I believe it's just an issue when coming from the copybook - shouldn't be an issue.

```rpgle
**free
dcl-ds DSAnagraficaArbitri qualified;
  Matricola char(1);
  Cognome char(35);
  Nome char(35);
  CodiceFiscale char(16);
  Localita char(35);
  Indirizzo char(35);
  CAP char(9);
  IBAN char(27);
  DataNascita char(10);
  LuogoNascita char(35);
  ProvinciaNascita char(2);
  Nazionalita char(2);
  Sesso char(1);
  Telefono char(14);
  Cellulare char(14);
  Email char(50);
end-ds;
```

<img width="499" alt="image" src="https://github.com/codefori/vscode-rpgle/assets/3708366/dda003d0-d2f7-499b-b630-340c73afd3ef">

<img width="530" alt="image" src="https://github.com/codefori/vscode-rpgle/assets/3708366/691bd400-688e-4627-82b7-b56e0fb2887e">
