### ISSUE TITLE
CompletionItemProvider locating currentprocedure in wrong source

### ISSUE THREAD

**Issue by EVLSDE** [codefori/vscode-rpgle#323]
**Describe the bug**
If you use copybooks with procedure prototypes inside you'll find vs code intellisense behaving strange: the list of suggestions doesn't match with your source at all.

**To Reproduce**
Define a copybook with a procedure prototype definition on a specific range of code lines, e.g. from line no. 10 to 12:

```
**free








dcl-pr SomeProcedure;
  SomeParameter char(1);
end-pr;
```

Use a /copy statement to include the copybook and place a procedure inside, where the procedure body covers the same line number:
```
**free
  
/copy 'QCPYLESRC/somecopybook.rpgle'

dcl-proc ExportedProcedure export;
  dcl-pi *n;
    ExportParameter1 char(1);
    ExportParameter2 char(1);
  end-pi;

  
end-proc;
```

Now if you start typing on said lines (e.g. 10-12) in your rpg source, you won't be able to find local definitions (e.g. "ExportParameter1"), but will find parameter definitions from your copybook procedure prototype instead (e.g. "SomeParameter") - as if you were typing on the same line but in the copybook source.
If you instead start typing on another line where there's no definition (e.g. 14), you'll find the suggestions are correct.

**Expected behavior**
I'd expect to find the same local definitions as suggestions on every line of code in a procedure.

**Screenshots**
![Screenshot 2024-09-11 085536](https://github.com/user-attachments/assets/e62d4186-0804-49ca-9d45-a193a67e7684)
![Screenshot 2024-09-11 085554](https://github.com/user-attachments/assets/1a2be45c-ff40-4a16-9bef-0f2cd59eb67d)
![Screenshot 2024-09-11 085604](https://github.com/user-attachments/assets/ae6198e6-5b97-4e9e-9977-5a31de6022ae)
![Screenshot 2024-09-11 085612](https://github.com/user-attachments/assets/caa30d24-ad38-4281-9f9e-980583c28605)

**Environment**
* Extension version v0.26.8
* IBM i OS version 7.4

**Additional context**
I found out that in completionItem.ts, currentProcedure is only found by comparing line numbers of definitions, but file path isn't being compared. 
After I added the following code inside find() on line 34, the suggestions worked again for me:
`&& currentPath === proc.position.path`

I'm not sure if there's a reason why this check is missing but maybe you can consider this for a future fix.

**Comment by worksofliam** [comment]
Related PR release in 0.28.9.
